name: freelanceplus
description: A simple project/client manager

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  firebase_analytics: ^10.4.2
  firebase_core: ^2.13.1
  firebase_crashlytics: ^3.3.2
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.6
  flutter_form_builder: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_riverpod: ^2.3.6
  form_builder_validators: ^9.0.0
  freezed_annotation: ^2.2.0
  google_fonts: ^5.0.0
  intl: any
  json_annotation: ^4.8.1
  package_info_plus: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  riverpod_annotation: ^2.1.1
  sqflite: ^2.2.8+4
  sqflite_common_ffi: ^2.2.5

dev_dependencies:
  build_runner: ^2.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  riverpod_generator: ^2.2.3
  very_good_analysis: ^5.0.0+1

flutter_native_splash:
  color: "#ffffff"
  image: assets/img/splash.png
  color_dark: "#434343"
  image_dark: assets/img/splash.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/round_icon.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/img/
    - assets/google-fonts/Bree_Serif/
    - assets/google-fonts/Source_Sans_3/static/
